Redirect 50 crate patch paths to monorepo
Failed to redirect:
- grpcio-sys: Windows is unable to handle -std=c++11 introduced by aosp/3368998
- itertools: bindgen depends on an older version of itertools < 0.13.0
- num-bigint: Mac build failure due to the following logs:

thread 'main' panicked at /Volumes/Android/buildbot/src/android/netsim-dev/external/rust/android-crates-io/crates/num-bigint/build.rs:47:53:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

Will redirect them once each crate issues are resolved in netsim-dev

Test: ABTD
Bug: 365637024
Change-Id: I678852c9fc94fc1048929df1a2c857918846a251